replicaCount: 1
repository: wombach/docker-python-rest
pullPolicy: Always
tag: "1.0.0"
service:
  name: reverse-proxy
  type: ClusterIP
  externalPort: 5000
  internalPort: 5000
external_hostname: "aureliusdev.westeurope.cloudapp.azure.com"