---
elastic_search:
  name: elastic-search
  replicaCount: 1
  version: 8.2.2
  persistence:
    enabled: true
    # storageClass: "-"
    accessMode: ReadWriteOnce
    size: 4Gi

kibana:
  name: kibana
  replicaCount: 1
  version: 8.2.2

enterprise_search:
  name: enterprise-search
  replicaCount: 1
  version: 8.2.2


