{{- if .Values.envs.config -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka-ui.fullname" . }}
  labels:
    {{- include "kafka-ui.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.envs.config | nindent 2 }}
  SERVER_SERVLET_CONTEXT_PATH: /{{ .Release.Namespace }}{{ .Values.envs.config.SERVER_SERVLET_CONTEXT_PATH_PARTIAL}}
{{- end -}}