{{- if .Values.enabled }}
{{- if .Values.yamlApplicationConfig -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka-ui.fullname" . }}-fromvalues
  labels:
    {{- include "kafka-ui.labels" . | nindent 4 }}
data:
  config.yml: |
    {{ tpl ( .Files.Get "conf/application-config.yaml" ) . | indent 4}}
    # {{- toYaml .Values.yamlApplicationConfig | nindent 4}}
{{ end }}
{{- end }}