{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-{{ include "kafka-ui.fullname" . }}-fromvalues
  labels:
    {{- include "kafka-ui.labels" . | nindent 4 }}
data:
  config.yml: |
{{ tpl ( .Files.Get "conf/application_config.yaml" ) . | indent 4}}
{{- end }}