apiVersion: v1
metadata:
  creationTimestamp: "2022-05-09T19:54:43Z"
  name: auth-conf
  namespace: {{ .Release.Namespace }}
  resourceVersion: "1209790"
  uid: bbd70869-25d4-4f1c-9284-68aaad775972
data:
  auth.conf: "<Location /auth>\r\n    ProxyPass \"http://keycloak.{{ .Release.Namespace }}.svc.cluster.local:8080/auth\"\r\n
    \   ProxyPassReverse \"http://keycloak.{{ .Release.Namespace }}.svc.cluster.local:8080/auth\"\r\n</Location>\r\n"
kind: ConfigMap
