{{- if .Values.enabled }}
{{- if .Values.proxy.atlas2_enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-reverse-proxy-configs-atlas2-conf
data:
  atlas2.conf: |
{{ tpl ( .Files.Get "conf.d/atlas2.yaml" ) . | indent 4}}
{{- end }}
{{- end }}