{{- if .Values.enabled }}
{{- if .Values.proxy.keycloak_enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-reverse-proxy-configs-auth-conf
data:
  auth.conf: |
{{ tpl ( .Files.Get "conf.d/auth.yaml" ) . | indent 4}}
{{- end }}
{{- end }}