{{- if .Values.enabled }}
{{- if .Values.proxy.flink_enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-reverse-proxy-configs-flink-conf
data:
  flink.conf: |
{{ tpl ( .Files.Get "conf.d/flink.yaml" ) . | indent 4}}
{{- end }}
{{- end }}