apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels: {{ include "reverse-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.internalPort }}
      targetPort: {{ .Values.service.externalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector: {{ include "reverse-proxy.selectorLabels" . | nindent 4 }}
