apiVersion: v1
kind: PersistentVolume
metadata:
  name: key-cloak-pv
  labels:
    'app.kubernetes.io/name': 'key-cloak-pv'
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
  local:
    path: "/mnt/keycloak"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .Values.node_name }}
