apiVersion: v1
kind: ConfigMap
metadata:
  name: python-rest-configs-m4i-atlas-config
data:
  m4i_atlas_config.py: |
    config = {
        "atlas.server.url": "https://{{ .Values.external_hostname }}/{{ .Release.Namespace }}/atlas/atlas",
        "data2model.server.url": "http://python-rest.{{ .Release.Namespace }}.svc.cluster.local:5000/data2model"
    }