{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: python-rest-configs-m4i-atlas-config
data:
  m4i_atlas_config.py: |
    config = {
        "atlas.server.url": "atlas.{{ .Release.Namespace }}.svc.cluster.local:21000/api/atlas",
        "data2model.server.url": "http://python-rest.{{ .Release.Namespace }}.svc.cluster.local:5000/data2model"
    }
{{- end }}