apiVersion: v1
kind: ConfigMap
metadata:
  name: python-rest-configs-m4i-atlas-config
data:
  m4i_atlas_config.py: |
    config = {
        "atlas.server.url": "127.0.0.1:9100/atlas/atlas",
        "data2model.server.url": "http://localhost:5000/data2model"
    }