<Location /flink/>
ProxyPass "http://flink-jobmanager.{{ .Release.Namespace }}.svc.cluster.local:8081/"
ProxyPassReverse "http://flink-jobmanager.{{ .Release.Namespace }}.svc.cluster.local:8081/"
</Location>
