
#OIDCProviderMetadataURL https://{{ .Values.global.external_hostname }}/{{ .Release.Namespace }}/auth/realms/m4i/.well-known/openid-configuration
#OIDCRedirectURI https://{{ .Values.global.external_hostname }}/{{ .Release.Namespace }}/flink/
#OIDCCryptoPassphrase 144f9e52-1d14-498d-9f1f-8dae0e50e579
#OIDCClientID m4i_kafka-connect
# get secrtet from https://aureliusdev.westeurope.cloudapp.azure.com/anwo/auth/admin/realms/m4i/clients/a7bcc3d1-40e5-4119-99b8-2ae9bb4976d3/installation/providers/keycloak-oidc-keycloak-json
#OIDCClientSecret 144f9e52-1d14-498d-9f1f-8dae0e50e579
## See https://github.com/Reposoft/openidc-keycloak-test/issues/7
#OIDCProviderTokenEndpointAuth client_secret_basic
#OIDCRemoteUserClaim email
#OIDCScope "openid email"
#OIDCXForwardedHeaders X-Forwarded-Host

<Location /{{ .Release.Namespace }}/kafka-connect/>
#AuthType openid-connect
#Require valid-user
ProxyPass "http://kafka-connect.{{ .Release.Namespace }}.svc.cluster.local:8083/"
ProxyPassReverse "http://kafka-connect.{{ .Release.Namespace }}.svc.cluster.local:8083/"
</Location>