apiVersion: v1
kind: ConfigMap
metadata:
  name: atlas-application-properties-configmap
data:
  atlas-application.properties: |
{{ tpl ( .Files.Get "conf/atlas-application--properties.yaml" ) . | indent 4}}