apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "atlas.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "atlas.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "atlas.selectorLabels" . | nindent 8 }}
    spec:
      hostname: atlas
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.repository }}:{{ .Values.tag }}"
          imagePullPolicy: {{ .Values.pullPolicy }}
          ports:
            - containerPort: 21000
          command: [
              "/bin/bash",
              "-c",
              "/opt/apache-atlas-2.2.0/bin/startup.sh"
          ]
          volumeMounts:
            - name: atlas-prop
              mountPath: /opt/apache-atlas-2.2.0/conf/atlas-application.properties
              subPath: atlas-application.properties
      volumes:
        - name: atlas-prop
          configMap:
            name: atlas-configs