apiVersion: v1
kind: ConfigMap
metadata:
  name: users-credentials-properties-configmap
data:
  users-credentials.properties: |
{{ tpl ( .Files.Get "conf/users-credentials--properties.yaml" ) . | indent 4}}