apiVersion: batch/v1
kind: Job
metadata:
  name: post-install-hook
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: OnFailure
      containers:
      - name: post-install-job
        image: "aureliusatlas/atlas-post-install:main"
        env:
          - name: NAMESPACE
            value: "{{ .Release.Namespace }}"
          - name: ELASTIC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: elastic-search-es-elastic-user
                key: elastic
          - name: KEYCLOAK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keycloak-secret-user-admin
                key: password
          - name: KEYCLOAK_USERNAME
            value: atlas
          - name: KEYCLOAK_URL
            value: "https://{{ .Values.global.external_hostname }}/{{ .Release.Namespace }}/auth/"
          - name: ATLAS_URL
            value: "https://{{ .Values.global.external_hostname }}/{{ .Release.Namespace }}/atlas2/api/atlas"
          - name: ELASTIC_URL
            value: "https://{{ .Values.global.external_hostname }}/{{ .Release.Namespace }}/elastic/"
          - name: ENTERPRISE_SEARCH_URL
            value: "https://{{ .Values.global.external_hostname }}/{{ .Release.Namespace }}/app-search/"
